[project]
name = "scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "holidays>=0.89",
    "ipykernel>=7.1.0",
    "ortools>=9.15.6755",
    "pandas>=3.0.0",
    "polars>=1.37.1",
]
